move who_am_i() after soft reset and SPI toggle
Testing on m5stampfly the BMI270 IMU is not recognized
due to failed who_am_i() returning 255, rather than the ID 0x24.
This problem is caused because who_am_i() is called before
soft reset and SPI toggle.

** Without patch **
Arduino library: Arduino-ESP32 v2.0.17
Board: ESP32-S3 DevKitC-1 (default board)
Processor: ESP32-S3
-D ARDUINO_BOARD=Espressif ESP32-S3-DevKitC-1-N8 (8 MB QD, No PSRAM)
-D ARDUINO_VARIANT=esp32s3
-D ARDUINO=10812
-D ARDUINO_RUNNING_CORE=1
-D ARDUINO_EVENNO_USB_CDC_ON_BOOT=1
CFG: Loading EEPROM - OK
CFG: Loading config - madflight_board loaded OK, madflight_config loaded OK
I2C: Scanning i2c_bus:0 - 0x10(16) 0x29(41) 0x40(64) 0x76(118) - Found 4 device(s)
LED: RGB
RCL: Channels: roll:1 pitch:2 throttle:3 yaw:4 armed:5 flightmode:6
BAR: BMP280
BAR: BMP280 i2c_adr=0x00 SensorID=0x58
MAG: NONE
BAT: NONE
RDR: NONE
OFL: PMW3901
GPS: NONE
ALT: KALMAN3  altCov=0.200000 accCov=0.010000 biasCov=0.100000
AHR: MAHONY
IMU: BMI270
IMU: , check pin/bus/bus_type config
FATAL ERROR: IMU install failed. - Type 'help' for help...

** With patch **
Arduino library: Arduino-ESP32 v2.0.17
Board: ESP32-S3 DevKitC-1 (default board)
Processor: ESP32-S3
-D ARDUINO_BOARD=Espressif ESP32-S3-DevKitC-1-N8 (8 MB QD, No PSRAM)
-D ARDUINO_VARIANT=esp32s3
-D ARDUINO=10812
-D ARDUINO_RUNNING_CORE=1
-D ARDUINO_EVENT_RUNNING_CORE=1
-D ARDUINO_USB_MODE=1
-D ARDUINO_USB_CDC_ON_BOOT=1
CFG: Loading EEPROM - OK
CFG: Loading config - madflight_board loaded OK, madflight_config loaded OK
I2C: Scanning i2c_bus:0 - 0x10(16) 0x40(64) 0x76(118) - Found 4 device(s)
LED: RGB
RCL: NONE - Channels: roll:1 pitch:2 throttle:3 yaw:4 armed:5 flightmode:6
BAR: BMP280
BAR: BMP280 i2c_adr=0x00 SensorID=0x58
MAG: NONE
BAT: NONE
RDR: NONE
OFL: PMW3901
GPS: NONE
ALT: KALMAN3  altCov=0.200000 accCov=0.010000 biasCov=0.100000
AHR: MAHONY
IMU: BMI270
IMU: IMU_EXEC_FREERTOS
AHR: No Magnetometer, yaw:0.00
OUT: idx:gpio:type = 0:G41:Brushed 1:G42:Brushed 2:G10:Brushed 3:G5:Brushed
Setup completed, CLI started - Type 'help' for help, or 'diff' to debug